### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by powerdollkirby** [t4bby/rover-on-linux#1]
followed each step
doesn't work
tried to get around it using wine ge, still doesn't work

launcher re opens itself when pressing start game

**Comment by mkrsym1** [comment]
That is because this is not a full bypass and still requires TPShell to fully load. That only happens on full GE-Proton. This will not work on other Wine versions

**Comment by t4bby** [comment]
Closing this because you are not using the `ProtonGE` that the guide required. Make sure you are using the correct version as I have used on the guide.

**Comment by powerdollkirby** [comment]
bruh what 
i'm using proton u idiot lol
i said even when using wine ge it still doesn't work
shitty bypass
